Vagrant.configure("2") do |config|

  # General Vagrant VM configuration.
  config.vm.synced_folder "../global-data", "/vagrant-data-sync"

  config.vm.define "node" do |app|
    app.vm.hostname = "node.192.168.55.10.xip.io"
    app.vm.network :private_network, ip: "192.168.55.10"
    app.vm.box = "ubuntu/bionic64"

    app.vm.provider "virtualbox" do |vb|
      vb.name = "basic-labs"
      vb.memory = "1024"
      vb.cpus = "1"

      file_to_disk = 'disk2.vdi'
      unless File.exist?(file_to_disk)
        vb.customize ['createhd', '--filename', file_to_disk, '--size', 3 * 1024] # add 3 GB disk
      end
      vb.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]

    end

  end

  config.vm.provision "shell", inline: "uname -a"

end