Vagrant.configure("2") do |config|

  # General Vagrant VM configuration.
  config.vm.synced_folder "../global-data", "/vagrant-data-sync"

  config.vm.define "node" do |app|
    app.vm.hostname = "node.192.168.55.10.xip.io"
    app.vm.network :private_network, ip: "192.168.55.10"
    app.vm.box = "ubuntu/bionic64"
    
    app.vm.provider "virtualbox" do |vb|
      vb.name = "basic-labs"
      vb.memory = "1024"
      vb.cpus = "1"
    end

  end

  config.vm.provision "shell", inline: "uname -a"

end