Vagrant.configure("2") do |config|

  # General Vagrant VM configuration.
  config.vm.box = "centos/7"
  
  config.vm.hostname = "basic-labs"
  config.vm.network "private_network", ip: "192.168.55.10"

  config.vm.synced_folder "../global-data", "/vagrant-data-sync"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "basic-labs-centos"
    vb.memory = "1024"
    vb.cpus = "2"
  end

  config.vm.provision "shell", inline: "yum update -y"

end