Vagrant.configure("2") do |config|

    # General Vagrant VM configuration.
    config.vm.synced_folder "../global-data", "/vagrant-data-sync"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end

    # Application 0.
    config.vm.define "master" do |app|
        # app.name = "vm-master"
        app.vm.hostname = "master.192.168.55.11.xip.io"
        app.vm.network :private_network, ip: "192.168.55.11"
        app.vm.box = "centos/7"
    end

    # Application 1.
    config.vm.define "node" do |app|
        # app.name = "vm-node"
        app.vm.hostname = "master.192.168.55.12.xip.io"
        app.vm.network :private_network, ip: "192.168.55.12"
        app.vm.box = "ubuntu/bionic64"
    end

  end