Vagrant.configure("2") do |config|

    # General Vagrant VM configuration.
    config.vm.synced_folder "../global-data", "/vagrant-data-sync"

    # Application 0.
    config.vm.define "master" do |app|

        app.vm.hostname = "master.192.168.55.11.xip.io"
        app.vm.network :private_network, ip: "192.168.55.11"
        app.vm.box = "centos/7"

        app.vm.provider "virtualbox" do |vb|
           vb.name = "master-centos"
           vb.memory = "1024"
           vb.cpus = "1"

           file_to_disk = 'disk2-master-centos.vdi'
           unless File.exist?(file_to_disk)
               vb.customize ['createhd', '--filename', file_to_disk, '--size', 2 * 1024] # add 2 GB disk
           end
           vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]

        end

    end

    # Application 1.
    config.vm.define "node" do |app|

        app.vm.hostname = "node.192.168.55.12.xip.io"
        app.vm.network :private_network, ip: "192.168.55.12"
        app.vm.box = "ubuntu/bionic64"

        config.vm.provider "virtualbox" do |vb|
            vb.name = "node-ubuntu"
            vb.memory = "1024"
            vb.cpus = "1"
            
        end

    end

  end