Vagrant.configure("2") do |config|

    # General Vagrant VM configuration.
    config.vm.synced_folder "../global-data", "/vagrant-data-sync"

    NODE_COUNT = 2
    NODE_COUNT.times do |i|
      machine_id = "vm-node-#{i+1}"
      config.vm.define machine_id do |machine|
        machine.vm.hostname = "vm-node-#{i+1}.192.168.55.1#{i+1}.xip.io"
        machine.vm.network :private_network, ip: "192.168.55.1#{i+1}" 
        machine.vm.box = "centos/7" 
        machine.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = "1"
          vb.name = machine_id
          vb.linked_clone = true
        end
      end
    end

  end